server:
  port: "8080"
  allow_origins: "*"

firebase:
  credentials_file: "../firebase-credentials.json"
  project_id: "letsnormalizeit-e8dd7"

mongodb:
  uri: "mongodb://localhost:27017"
  database: "letsnormalizeit"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
